### ISSUE TITLE
Successful scramble votes should end the current round and restart immediately.

### ISSUE THREAD

**Issue by eedefeed** [CreatorsTF/gameservers#30]
There are probably people who take a different view, but voting to scramble is a clear "no-one is having fun here" from the server. Why drag people through an additional 1-3 minutes of not enjoying themselves before rolling the dice and hoping there's not another roll.

**Comment by xNanochip** [comment]
I pushed a change into this coming Friday's release that will make it so the scramble will immediately happen most of the time, however it will wait till next round if the round is close to ending, which is determined by these conditions: https://github.com/CreatorsTF/gameservers/blob/stable/tf/addons/sourcemod/scripting/fixauto.sp#L19-L29

The reason why I've made it wait till next round under the above conditions is so that it doesn't disrupt gameplay, similar to the reason why we disable autobalance during those conditions.

**Comment by sapphonie** [comment]
43cacf450da546db7a9cc22188eb85cc39036b3e
